name: Build
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            os_short: linux
            ext: .so
          - os: windows-latest
            os_short: windows
            ext: .dll
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os_short }}-x86
    steps:
      - uses: actions/checkout@v6
        with:
          path: project

      - name: Checkout SourceMod
        uses: actions/checkout@v6
        with:
          repository: alliedmodders/sourcemod
          ref: 1.12-dev
          submodules: recursive
          path: sourcemod

      - name: Checkout Metamod:Source
        uses: actions/checkout@v6
        with:
          repository: alliedmodders/metamod-source
          ref: 1.12-dev
          path: metamod-source

      - uses: actions/setup-python@v6
        name: Setup Python
        with:
          python-version: '3.13'

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install AMBuild
        run: |
          git clone https://github.com/alliedmodders/ambuild.git
          cd ambuild
          python setup.py install --user

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            gcc-multilib g++-multilib libstdc++6 lib32stdc++6 \
            libc6-dev-i386 linux-libc-dev:i386

      - name: Build
        working-directory: project
        shell: bash
        run: |
          mkdir build && cd build
          python ../configure.py \
            --sm-path="${{ github.workspace }}/sourcemod" \
            --mms-path="${{ github.workspace }}/metamod-source" \
            --enable-optimize \
            --targets=x86
          ambuild

      - name: Stage release files
        shell: bash
        run: |
          mkdir -p staging/addons/sourcemod/extensions
          find project/build -name '*${{ matrix.ext }}' -exec cp {} staging/addons/sourcemod/extensions/ \;
          touch staging/addons/sourcemod/extensions/sm-extension.autoload

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: sm-extension-${{ matrix.os_short }}
          path: staging/*
